# Generated by Django 4.2.16 on 2024-12-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_sql', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя покупателя')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Баланс')),
                ('age', models.IntegerField(verbose_name='Возраст')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название игры')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('size', models.IntegerField(verbose_name='Размер (МБ)')),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
